stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    outs:
    - evaluation/importance.csv
    - evaluation/shap.png
    - evaluation/test/plots:
        cache: false
    - evaluation/train/plots:
        cache: false
    metrics:
    - evaluation/test.json:
        cache: false
    - evaluation/train.json:
        cache: false
plots:
  ROC:
    x: fpr
    y:
      evaluation/train/plots/roc.json: tpr
      evaluation/test/plots/roc.json: tpr
  Precision-Recall:
    x: recall
    y:
      evaluation/test/plots/precision_recall.json: precision
  Confusion-Matrix:
    template: confusion
    x: actual
    y:
      evaluation/train/plots/confusion_matrix.json: predicted
      evaluation/test/plots/confusion_matrix.json: predicted
  evaluation/importance.csv:
    title: Feature Importance
    template: bar_horizontal_sorted
    x: Mean decrease in impurity
    y: Feature
  evaluation/shap.png:
    title: SHAP Feature Importance
